#!/usr/bin/env bash
# Generate apps/api/.env and apps/web/.env from a running local Supabase stack.
# Requires: supabase CLI, `supabase start` already running.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

API_ENV="$REPO_ROOT/apps/api/.env"
WEB_ENV="$REPO_ROOT/apps/web/.env"
CONFIG_TOML="$REPO_ROOT/supabase/config.toml"

PORT="${PORT:-3001}"
WEB_ORIGIN="${WEB_ORIGIN:-http://localhost:3000}"
API_PUBLIC_URL="${API_PUBLIC_URL:-http://localhost:${PORT}}"

usage() {
  cat <<'EOF'
Usage: setup-local-env.sh [options]

Write local dev .env files using `supabase status -o env`.

Options:
  --dry-run          Print files to stdout instead of writing
  --non-interactive  Skip prompts (SEARCH_API_KEY stays empty unless already in apps/api/.env)
  -h, --help         Show this help

Environment overrides (optional):
  PORT              Nest API port (default: 3001)
  WEB_ORIGIN        CORS / app origin (default: http://localhost:3000)
  API_PUBLIC_URL    PUBLIC_API_URL / NEXT_PUBLIC_API_URL (default: http://localhost:$PORT)
  MEDIA_BUCKET      Storage bucket name (default: first [storage.buckets.*] in config.toml, else "media")
  SEARCH_API_KEY    Tavily key for PDF import web lookup (optional; prompted when interactive)
EOF
}

dry_run=false
non_interactive=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) dry_run=true; shift ;;
    --non-interactive) non_interactive=true; shift ;;
    -h | --help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
done

read_env_var() {
  local file="$1"
  local key="$2"
  [[ -f "$file" ]] || return 1
  grep -E "^${key}=" "$file" 2>/dev/null | tail -1 | sed -E "s/^${key}=//"
}

is_placeholder_encryption_key() {
  local val="$1"
  [[ -z "$val" || "$val" == "change-me-to-a-long-random-secret" ]]
}

generate_encryption_key() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32
  else
    head -c 32 /dev/urandom | base64 | tr -d '\n'
  fi
}

prompt_search_api_key() {
  if [[ -n "${SEARCH_API_KEY:-}" ]]; then
    return
  fi
  if $non_interactive || ! [[ -t 0 ]]; then
    return
  fi

  cat <<'EOF'

PDF import — optional web lookup (Tavily)
---------------------------------------
The import agent can resolve company/school URLs during PDF import when
SEARCH_API_KEY is set. Without it, web lookup is skipped; import still works.

Get a free API key:
  1. Sign up at https://tavily.com
  2. Open Dashboard → API keys
  3. Create a key and paste it below

Press Enter to skip.
EOF
  read -r -p "SEARCH_API_KEY: " entered_key || true
  if [[ -n "${entered_key// /}" ]]; then
    SEARCH_API_KEY="$entered_key"
  fi
}

if ! command -v supabase >/dev/null 2>&1; then
  echo "error: supabase CLI not found (https://supabase.com/docs/guides/cli)" >&2
  exit 1
fi

cd "$REPO_ROOT"

if ! supabase status -o env >/dev/null 2>&1; then
  echo "error: failed to read Supabase status — is \`supabase start\` running?" >&2
  exit 1
fi

# stderr may include "Stopped services: ..." — only eval stdout KEY="value" lines.
status_env="$(supabase status -o env 2>/dev/null)"

# shellcheck disable=SC1090
eval "$status_env"

for var in API_URL ANON_KEY SERVICE_ROLE_KEY JWT_SECRET; do
  if [[ -z "${!var:-}" ]]; then
    echo "error: supabase status did not provide $var" >&2
    exit 1
  fi
done

media_bucket="${MEDIA_BUCKET:-}"
if [[ -z "$media_bucket" && -f "$CONFIG_TOML" ]]; then
  media_bucket="$(
    grep -E '^\[storage\.buckets\.' "$CONFIG_TOML" \
      | head -1 \
      | sed -E 's/^\[storage\.buckets\.([^]]+)\].*$/\1/'
  )"
fi
media_bucket="${media_bucket:-media}"

existing_encryption_key=""
existing_search_api_key=""
if [[ -f "$API_ENV" ]]; then
  existing_encryption_key="$(read_env_var "$API_ENV" IMPORT_LLM_CONFIG_ENCRYPTION_KEY || true)"
  existing_search_api_key="$(read_env_var "$API_ENV" SEARCH_API_KEY || true)"
fi

encryption_key_rotated=false
if is_placeholder_encryption_key "$existing_encryption_key"; then
  import_llm_config_encryption_key="$(generate_encryption_key)"
  if [[ -n "$existing_encryption_key" ]]; then
    encryption_key_rotated=true
  fi
else
  import_llm_config_encryption_key="$existing_encryption_key"
fi

SEARCH_API_KEY="${SEARCH_API_KEY:-$existing_search_api_key}"
prompt_search_api_key

pdf_import_max_bytes="${PDF_IMPORT_MAX_BYTES:-5242880}"
pdf_import_enabled="${PDF_IMPORT_ENABLED:-true}"

api_env_content="$(cat <<EOF
# Generated by scripts/setup-local-env.sh — re-run after \`supabase start\` / key changes.
# Source: supabase status -o env

SUPABASE_URL=${API_URL}
SUPABASE_ANON_KEY=${ANON_KEY}

# Server-only: Storage uploads (\`POST /media/upload\`)
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
MEDIA_BUCKET=${media_bucket}

# Optional legacy JWT secret — not required for API auth validation
SUPABASE_JWT_SECRET=${JWT_SECRET}

PORT=${PORT}
CORS_ORIGIN=${WEB_ORIGIN}
APP_URL=${WEB_ORIGIN}
PUBLIC_API_URL=${API_PUBLIC_URL}

# PDF import + per-user LLM settings
IMPORT_LLM_CONFIG_ENCRYPTION_KEY=${import_llm_config_encryption_key}
SEARCH_API_KEY=${SEARCH_API_KEY}
PDF_IMPORT_MAX_BYTES=${pdf_import_max_bytes}
PDF_IMPORT_ENABLED=${pdf_import_enabled}
EOF
)"

web_env_content="$(cat <<EOF
# Generated by scripts/setup-local-env.sh
# Browser → Nest API over CORS (Bearer JSON). Supabase is server-side only (apps/api).

NEXT_PUBLIC_API_URL=${API_PUBLIC_URL}
EOF
)"

write_file() {
  local path="$1"
  local content="$2"
  if $dry_run; then
    printf '\n--- %s ---\n' "$path"
    printf '%s\n' "$content"
    return
  fi
  mkdir -p "$(dirname "$path")"
  printf '%s\n' "$content" >"$path"
  echo "Wrote $path"
}

write_file "$API_ENV" "$api_env_content"
write_file "$WEB_ENV" "$web_env_content"

if ! $dry_run; then
  echo "Local env ready (SUPABASE_URL=${API_URL}, MEDIA_BUCKET=${media_bucket})"
  if [[ -z "$existing_encryption_key" ]]; then
    echo "Generated IMPORT_LLM_CONFIG_ENCRYPTION_KEY for PDF import LLM settings."
  elif $encryption_key_rotated; then
    echo "Rotated IMPORT_LLM_CONFIG_ENCRYPTION_KEY — re-save import LLM settings at /dashboard/settings/import-llm if PDF import fails."
  fi
  if [[ -z "${SEARCH_API_KEY:-}" ]]; then
    echo "SEARCH_API_KEY not set — PDF import web lookup disabled (optional)."
  fi
fi
